#!/bin/bash

set -e

BITLBEE_CONF=${BITLBEE_CONF:-/etc/bitlbee/bitlbee.conf}
BITLBEE_DATA_DIR=${BITLBEE_DATA_DIR:-/data/bitlbee}

BITLBEE_INTERFACE=${BITLBEE_INTERFACE:-127.0.0.1}
BITLBEE_PORT=${BITLBEE_PORT:-6688}
BITLBEE_CLIENT_INTERFACE=${BITLBEE_CLIENT_INTERFACE:-0.0.0.0}
BITLBEE_AUTH_MODE=${BITLBEE_AUTH_MODE:-Open}
BITLBEE_AUTH_PASSWORD=${BITLBEE_AUTH_PASSWORD:-}
BITLBEE_OPER_PASSWORD=${BITLBEE_OPER_PASSWORD:-}
BITLBEE_HOSTNAME=${BITLBEE_HOSTNAME:-}
BITLBEE_MOTD_FILE=${BITLBEE_MOTD_FILE:-/etc/bitlbee/motd.txt}

BITLBEE_CONFIG_DIR=${BITLBEE_CONFIG_DIR:-${BITLBEE_DATA_DIR}}
BITLBEE_PING_TIMEOUT=${BITLBEE_PING_TIMEOUT:-0}
BITLBEE_PROXY=${BITLBEE_PROXY:-}
BITLBEE_PROTOCOL=${BITLBEE_PROTOCOL:-}

sed -i 's/{{BITLBEE_INTERFACE}}/'"${BITLBEE_INTERFACE}"'/g' $BITLBEE_CONF
sed -i 's/{{BITLBEE_PORT}}/'"${BITLBEE_PORT}"'/g' $BITLBEE_CONF
sed -i 's/{{BITLBEE_CLIENT_INTERFACE}}/'"${BITLBEE_CLIENT_INTERFACE}"'/g' $BITLBEE_CONF
sed -i 's/{{BITLBEE_AUTH_MODE}}/'"${BITLBEE_AUTH_MODE}"'/g' $BITLBEE_CONF
sed -i 's/{{BITLBEE_AUTH_PASSWORD}}/'"${BITLBEE_AUTH_PASSWORD}"'/g' $BITLBEE_CONF
[ -n "${BITLBEE_AUTH_PASSWORD}" ] && sed -i 's/^#AuthPassword/AuthPassword/g' $BITLBEE_CONF
sed -i 's/{{BITLBEE_OPER_PASSWORD}}/'"${BITLBEE_OPER_PASSWORD}"'/g' $BITLBEE_CONF
[ -n "${BITLBEE_OPER_PASSWORD}" ] && sed -i 's/^#OperPassword/OperPassword/g' $BITLBEE_CONF
sed -i 's/{{BITLBEE_HOSTNAME}}/'"${BITLBEE_HOSTNAME}"'/g' $BITLBEE_CONF
[ -n "${BITLBEE_HOSTNAME}" ] && sed -i 's/^#HostName/HostName/g' $BITLBEE_CONF
sed -i 's,{{BITLBEE_MOTD_FILE}},'"${BITLBEE_MOTD_FILE}"',g' $BITLBEE_CONF
touch "${BITLBEE_MOTD_FILE}"
sed -i 's,{{BITLBEE_CONFIG_DIR}},'"${BITLBEE_CONFIG_DIR}"',g' $BITLBEE_CONF
mkdir -p ${BITLBEE_CONFIG_DIR}
chown -R bitlbee:bitlbee ${BITLBEE_CONFIG_DIR}
sed -i 's/{{BITLBEE_PING_TIMEOUT}}/'"${BITLBEE_PING_TIMEOUT}"'/g' $BITLBEE_CONF
sed -i 's,{{BITLBEE_PROXY}},'"${BITLBEE_PROXY}"',g' $BITLBEE_CONF
[ -n "${BITLBEE_PROXY}" ] && sed -i 's/^#Proxy/Proxy/g' $BITLBEE_CONF
sed -i 's/{{BITLBEE_PROTOCOLS}}/'"${BITLBEE_PROTOCOLS}"'/g' $BITLBEE_CONF
[ -n "${BITLBEE_PROTOCOLS}" ] && sed -i 's/^#Protocols/Protocols/g' $BITLBEE_CONF

mkdir -p ${BITLBEE_DATA_DIR}
chown -R bitlbee:bitlbee ${BITLBEE_DATA_DIR}

exit 0
