#!/bin/bash

LOGDIR=/data/log
PGDATA=/data/pgdata

mkdir -p "$LOGDIR"
mkdir -p "$PGDATA"

chown -R postgres "$PGDATA"
if [ -z "$(ls -A $PGDATA)" ]; then
  su -c "initdb --locale en_US.UTF-8 -E UTF8 -D '$PGDATA'" - postgres

  sed -ri "s/^#(listen_addresses\s*=\s*)\S+/\1'*'/" "$PGDATA"/postgresql.conf
  { echo; echo 'host all all 0.0.0.0/0 trust'; } >> "$PGDATA"/pg_hba.conf
fi


exec 2>&1 \
  su -c "/usr/bin/postgres -D $PGDATA" - postgres 
