#!/bin/bash

PGDATA=${PGDATA:-/data/pgdata}

mkdir -p "/run/postgresql"
mkdir -p "$PGDATA"

chown -R postgres "$PGDATA"
chown -R postgres "/run/postgresql"
if [ -z "$(ls -A $PGDATA)" ]; then
  su -c "initdb --locale en_US.UTF-8 -E UTF8 -D '$PGDATA'" - postgres

  sed -ri "s/^#(listen_addresses\s*=\s*)\S+/\1'*'/" "$PGDATA"/postgresql.conf
  { echo; echo 'host all all 0.0.0.0/0 trust'; } >> "$PGDATA"/pg_hba.conf
fi


exec 2>&1 \
  su -c "/usr/bin/postgres -D $PGDATA" - postgres 
